# Generated by Django 4.1.7 on 2023-03-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPage1',
            new_name='Page1',
        ),
    ]
