# Generated by Django 4.1.7 on 2023-03-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_portfoliopage1_page1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='page1',
            old_name='lastname',
            new_name='lname',
        ),
    ]
