# Generated by Django 4.1.7 on 2023-03-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_firstname_page1_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='Prof',
            new_name='prof',
        ),
    ]
