# Generated by Django 4.1.7 on 2023-03-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_prof_page1_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
