# Generated by Django 4.1.7 on 2023-03-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_skill1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('uni', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
            ],
        ),
    ]
